name: Markdown Linting Action
description: GitHub Action to run markdown linter
author: avto-dev

inputs: # <https://git.io/JvkYF#inputs>
  rules:
    description: 'Custom rule files (file|directory|glob|package)'
    required: false
  config:
    description: 'Configuration file (JSON, JSONC, or YAML)'
    required: false
  fix:
    description: 'Fix basic errors (set "true")'
    required: false
  output:
    description: 'Write issues to file'
    required: false
  ignore:
    description: 'Files to ignore/exclude'
    required: false
  path:
    description: 'Files (directories|globs) for a work'
    required: true

runs: # <https://git.io/JvkYF#runs>
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.target }}

branding: # <https://git.io/JvkYF#branding>
  icon: file-text
  color: green
